# Generated by Django 3.1.2 on 2020-10-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='lyrics',
            field=models.CharField(max_length=2048),
        ),
    ]
